version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "frontend"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      npm-frontend-updates: # Added group
        patterns:
          - "*"

  # Root npm workspace
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "workspace"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      npm-root-updates: # Added group
        patterns:
          - "*"

  # Backend Python dependencies
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "backend"
      - "python"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      pip-backend-updates: # Added group
        patterns:
          - "*"

  # AI Engine Python dependencies
  - package-ecosystem: "pip"
    directory: "/ai-engine"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ai-engine"
      - "python"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      pip-ai-engine-updates: # Added group
        patterns:
          - "*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      docker-root-updates: # Added group
        patterns:
          - "*"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 1 # Changed from 10
    groups:
      github-actions-root-updates: # Added group
        patterns:
          - "*"