# Fly.io Deployment Configuration for ModPorter AI
# Usage: flyctl deploy -c deploy-fly.toml

app = "modporter-ai"
primary_region = "iad"  # US East (Ashburn) - change as needed

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.fly"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"
  DOMAIN = "modporter.ai"
  API_URL = "https://modporter.ai/api/v1"
  API_BASE_URL = "https://modporter.ai"
  FRONTEND_URL = "https://modporter.ai"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[http_service.concurrency]
  type = "requests"
  hard_limit = 200
  soft_limit = 100

# Frontend service
[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["frontend"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 200
    soft_limit = 100

# Backend API service  
[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["backend"]

  [[services.ports]]
    port = 8080
    handlers = ["http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 100
    soft_limit = 50

# AI Engine service
[[services]]
  protocol = "tcp"
  internal_port = 8001
  processes = ["ai-engine"]

  [[services.ports]]
    port = 8001
    handlers = ["http"]

  [services.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5

# Machine specifications
[machine]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2

# Volume for persistent data
[[mounts]]
  source = "modporter_data"
  destination = "/data"
  initial_size = "10gb"

# Scaling configuration
[scaling]
  min_machines_running = 1
  max_machines_running = 10

  [[scaling.regions]]
    code = "iad"
    min_machines_running = 1

  [[scaling.regions]]
    code = "lhr"  # London for EU users
    min_machines_running = 0

# Environment variables (secrets set via flyctl)
# Run: flyctl secrets set KEY=value
[env_vars]
  REDIS_URL = "redis://modporter-redis.internal:6379"
  DATABASE_URL = "postgresql://postgres:password@modporter-postgres.internal:5432/modporter"