/**
 * Batch Download & Report Component
 * Task 1.5.2.5: Enable batch download and reporting
 * 
 * Features:
 * - ZIP all completed conversions
 * - Batch summary report
 * - Individual reports included
 * - Download progress
 */

import React, { useState, useCallback } from 'react';
import {
  useSuccessNotification,
  useErrorNotification,
} from '../NotificationSystem';
import { API_BASE_URL, downloadBatchResults } from '../../services/api';
import './BatchDownloadReport.css';

export interface BatchItemResult {
  itemId: string;
  filename: string;
  status: 'completed' | 'failed';
  error?: string;
  resultPath?: string;
}

export interface BatchSummary {
  batchId: string;
  totalItems: number;
  completedItems: number;
  failedItems: number;
  successRate: number;
  startTime: string;
  endTime: string;
  duration: number;
  version: string;
}

interface BatchDownloadReportProps {
  batchId: string;
  items: BatchItemResult[];
  summary: BatchSummary;
  onDownloadComplete?: () => void;
}

export const BatchDownloadReport: React.FC<BatchDownloadReportProps> = ({
  batchId,
  items,
  summary,
  onDownloadComplete,
}) => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadProgress, setDownloadProgress] = useState(0);
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  
  const successNotification = useSuccessNotification();
  const errorNotification = useErrorNotification();

  // Download all as ZIP
  const downloadAllAsZip = useCallback(async () => {
    setIsDownloading(true);
    setDownloadProgress(0);

    try {
      // Simulate progress
      const progressInterval = setInterval(() => {
        setDownloadProgress(prev => Math.min(prev + 10, 90));
      }, 200);

      const { blob, filename } = await downloadBatchResults(batchId);

      clearInterval(progressInterval);
      setDownloadProgress(100);

      // Trigger download
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      successNotification(`Batch downloaded: ${filename}`);
      onDownloadComplete?.();
    } catch (err) {
      console.error('Download failed:', err);
      errorNotification('Failed to download batch');
    } finally {
      setIsDownloading(false);
      setDownloadProgress(0);
    }
  }, [batchId, successNotification, errorNotification, onDownloadComplete]);

  // Generate and download batch report
  const generateReport = useCallback(async (format: 'json' | 'markdown') => {
    setIsGeneratingReport(true);

    try {
      const completedItems = items.filter(i => i.status === 'completed');
      const failedItems = items.filter(i => i.status === 'failed');

      let content: string;
      let filename: string;
      let mimeType: string;

      if (format === 'markdown') {
        // Generate markdown report
        content = `# Batch Conversion Report

## Summary

| Metric | Value |
|--------|-------|
| Batch ID | ${batchId.slice(0, 8)} |
| Total Items | ${summary.totalItems} |
| Completed | ${summary.completedItems} |
| Failed | ${summary.failedItems} |
| Success Rate | ${summary.successRate.toFixed(1)}% |
| Start Time | ${new Date(summary.startTime).toLocaleString()} |
| End Time | ${new Date(summary.endTime).toLocaleString()} |
| Duration | ${formatDuration(summary.duration)} |
| Target Version | ${summary.version} |

## Completed Mods

${completedItems.map(item => `- ✅ ${item.filename}`).join('\n')}

${failedItems.length > 0 ? `## Failed Mods

${failedItems.map(item => `- ❌ ${item.filename}${item.error ? `: ${item.error}` : ''}`).join('\n')}` : ''}

---
*Generated by ModPorter AI*
`;
        filename = `batch-report-${batchId.slice(0, 8)}.md`;
        mimeType = 'text/markdown';
      } else {
        // Generate JSON report
        const report = {
          batchId,
          summary: {
            ...summary,
            successRate: `${summary.successRate.toFixed(1)}%`,
          },
          completed: completedItems.map(i => ({
            filename: i.filename,
            status: i.status,
            resultPath: i.resultPath,
          })),
          failed: failedItems.map(i => ({
            filename: i.filename,
            status: i.status,
            error: i.error,
          })),
          generatedAt: new Date().toISOString(),
        };
        content = JSON.stringify(report, null, 2);
        filename = `batch-report-${batchId.slice(0, 8)}.json`;
        mimeType = 'application/json';
      }

      // Download report
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      successNotification(`Report downloaded: ${filename}`);
    } catch (err) {
      console.error('Report generation failed:', err);
      errorNotification('Failed to generate report');
    } finally {
      setIsGeneratingReport(false);
    }
  }, [batchId, items, summary, successNotification, errorNotification]);

  // Format duration
  const formatDuration = (seconds: number): string => {
    if (seconds < 60) return `${seconds}s`;
    if (seconds < 3600) {
      const mins = Math.floor(seconds / 60);
      const secs = seconds % 60;
      return `${mins}m ${secs}s`;
    }
    const hours = Math.floor(seconds / 3600);
    const mins = Math.floor((seconds % 3600) / 60);
    return `${hours}h ${mins}m`;
  };

  const completedItems = items.filter(i => i.status === 'completed');
  const failedItems = items.filter(i => i.status === 'failed');

  return (
    <div className="batch-download-report">
      {/* Summary Section */}
      <div className="summary-section">
        <h3>Batch Summary</h3>
        
        <div className="summary-grid">
          <div className="summary-item">
            <span className="summary-label">Total</span>
            <span className="summary-value">{summary.totalItems}</span>
          </div>
          <div className="summary-item success">
            <span className="summary-label">Completed</span>
            <span className="summary-value">{summary.completedItems}</span>
          </div>
          <div className="summary-item error">
            <span className="summary-label">Failed</span>
            <span className="summary-value">{summary.failedItems}</span>
          </div>
          <div className="summary-item">
            <span className="summary-label">Success Rate</span>
            <span className="summary-value">{summary.successRate.toFixed(1)}%</span>
          </div>
        </div>

        <div className="summary-details">
          <div className="detail-row">
            <span className="detail-label">Duration:</span>
            <span className="detail-value">{formatDuration(summary.duration)}</span>
          </div>
          <div className="detail-row">
            <span className="detail-label">Target Version:</span>
            <span className="detail-value">{summary.version}</span>
          </div>
          <div className="detail-row">
            <span className="detail-label">Completed:</span>
            <span className="detail-value">{new Date(summary.endTime).toLocaleString()}</span>
          </div>
        </div>
      </div>

      {/* Download Section */}
      <div className="download-section">
        <h3>Download Results</h3>
        
        <div className="download-buttons">
          <button
            className="download-zip-button primary"
            onClick={downloadAllAsZip}
            disabled={isDownloading || completedItems.length === 0}
          >
            {isDownloading ? (
              <>
                <span className="spinner">⟳</span>
                Downloading... {downloadProgress}%
              </>
            ) : (
              <>
                📦 Download All as ZIP ({completedItems.length} files)
              </>
            )}
          </button>
        </div>

        {isDownloading && (
          <div className="download-progress">
            <div className="progress-bar">
              <div 
                className="progress-fill"
                style={{ width: `${downloadProgress}%` }}
              />
            </div>
          </div>
        )}
      </div>

      {/* Report Section */}
      <div className="report-section">
        <h3>Generate Report</h3>
        
        <div className="report-buttons">
          <button
            className="report-button"
            onClick={() => generateReport('markdown')}
            disabled={isGeneratingReport}
          >
            📄 Download Markdown Report
          </button>
          <button
            className="report-button"
            onClick={() => generateReport('json')}
            disabled={isGeneratingReport}
          >
            📋 Download JSON Report
          </button>
        </div>
      </div>

      {/* Item Details */}
      <div className="item-details-section">
        <h3>Conversion Details</h3>
        
        {completedItems.length > 0 && (
          <div className="completed-list">
            <h4>Completed ({completedItems.length})</h4>
            <ul>
              {completedItems.slice(0, 10).map(item => (
                <li key={item.itemId}>
                  <span className="status-icon success">✅</span>
                  <span className="filename">{item.filename}</span>
                </li>
              ))}
              {completedItems.length > 10 && (
                <li className="more">
                  +{completedItems.length - 10} more files
                </li>
              )}
            </ul>
          </div>
        )}

        {failedItems.length > 0 && (
          <div className="failed-list">
            <h4>Failed ({failedItems.length})</h4>
            <ul>
              {failedItems.slice(0, 10).map(item => (
                <li key={item.itemId}>
                  <span className="status-icon error">❌</span>
                  <span className="filename">{item.filename}</span>
                  {item.error && <span className="error-msg">{item.error}</span>}
                </li>
              ))}
              {failedItems.length > 10 && (
                <li className="more">
                  +{failedItems.length - 10} more files
                </li>
              )}
            </ul>
          </div>
        )}
      </div>
    </div>
  );
};

export default BatchDownloadReport;
