"""
Error Handlers - backward compatibility re-export.

This module now imports from errors.handler.
"""

from errors.handler import (
    ErrorResponse,
    ModPorterException,
    ConversionException,
    FileProcessingException,
    ValidationException,
    NotFoundException,
    RateLimitException,
    ParseError,
    AssetError,
    LogicError,
    PackageError,
    ERROR_CATEGORIES,
    ERROR_CODES,
    RETRYABLE_ERROR_CATEGORIES,
    NON_RETRYABLE_ERROR_CATEGORIES,
    _categorize_error,
    create_error_response,
    register_exception_handlers,
    verify_exception_handlers,
    modporter_exception_handler,
    http_exception_handler,
    validation_exception_handler,
    generic_exception_handler,
    is_debug_mode,
    DEBUG_MODE,
)

__all__ = [
    "ErrorResponse",
    "ModPorterException",
    "ConversionException",
    "FileProcessingException",
    "ValidationException",
    "NotFoundException",
    "RateLimitException",
    "ParseError",
    "AssetError",
    "LogicError",
    "PackageError",
    "ERROR_CATEGORIES",
    "ERROR_CODES",
    "RETRYABLE_ERROR_CATEGORIES",
    "NON_RETRYABLE_ERROR_CATEGORIES",
    "_categorize_error",
    "create_error_response",
    "register_exception_handlers",
    "verify_exception_handlers",
    "modporter_exception_handler",
    "http_exception_handler",
    "validation_exception_handler",
    "generic_exception_handler",
    "is_debug_mode",
    "DEBUG_MODE",
]
