"""add_comparison_tables

Revision ID: 0002_add_comparison_tables
Revises: 0001_initial
Create Date: 2023-10-27 10:00:00.000000 # Placeholder Create Date

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0002_add_comparison_tables"  # User-defined revision string
down_revision = "0001_initial"  # Points to the previous migration (0001_initial.py)
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "comparison_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("conversion_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "structural_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("code_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("asset_diff", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "assumptions_applied",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "confidence_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),  # Added timezone=True
        sa.ForeignKeyConstraint(
            ["conversion_id"],
            ["conversion_jobs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feature_mappings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("comparison_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("java_feature", sa.Text(), nullable=True),
        sa.Column("bedrock_equivalent", sa.Text(), nullable=True),
        sa.Column("mapping_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("confidence_score", sa.DECIMAL(precision=3, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["comparison_id"],
            ["comparison_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feature_mappings")
    op.drop_table("comparison_results")
    # ### end Alembic commands ###
