"""Add behavior_templates table

Revision ID: 0003_add_behavior_templates
Revises: 0002_add_addon_tables
Create Date: 2024-07-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_add_behavior_templates'
down_revision = '0002_add_addon_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create behavior_templates table
    op.create_table(
        'behavior_templates',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('category', sa.String(50), nullable=False),
        sa.Column('template_type', sa.String(100), nullable=False),
        sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'{}'::jsonb")),
        sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('version', sa.String(20), nullable=False, server_default=sa.text("'1.0.0'")),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id', ondelete='SET NULL'), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('NOW()'), onupdate=sa.text('NOW()')),
    )

    # Create indexes for performance
    op.create_index('ix_behavior_templates_category', 'behavior_templates', ['category'])
    op.create_index('ix_behavior_templates_template_type', 'behavior_templates', ['template_type'])
    op.create_index('ix_behavior_templates_is_public', 'behavior_templates', ['is_public'])
    op.create_index('ix_behavior_templates_name', 'behavior_templates', ['name'])
    op.create_index('ix_behavior_templates_tags', 'behavior_templates', ['tags'], postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_behavior_templates_tags', table_name='behavior_templates')
    op.drop_index('ix_behavior_templates_name', table_name='behavior_templates')
    op.drop_index('ix_behavior_templates_is_public', table_name='behavior_templates')
    op.drop_index('ix_behavior_templates_template_type', table_name='behavior_templates')
    op.drop_index('ix_behavior_templates_category', table_name='behavior_templates')
    op.drop_table('behavior_templates')
    # ### end Alembic commands ###
